/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coding;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author HP
 */
public class Decryption extends javax.swing.JFrame {

    BufferedImage Image = null;
    /**
     * Creates new form Decryption
     */
    public Decryption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMessage = new javax.swing.JTextArea();
        btnopen = new javax.swing.JButton();
        btndecode = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Decode Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        jTextMessage.setColumns(20);
        jTextMessage.setRows(5);
        jScrollPane1.setViewportView(jTextMessage);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );

        btnopen.setBackground(new java.awt.Color(255, 255, 0));
        btnopen.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btnopen.setForeground(new java.awt.Color(0, 0, 255));
        btnopen.setText("Open");
        btnopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenActionPerformed(evt);
            }
        });

        btndecode.setBackground(new java.awt.Color(255, 255, 51));
        btndecode.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btndecode.setForeground(new java.awt.Color(0, 51, 255));
        btndecode.setText("Decode");
        btndecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecodeActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 255, 51));
        btnreset.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(0, 51, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnopen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btndecode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnopen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndecode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private File showFileDialog(final boolean open){
    JFileChooser fc = new JFileChooser("Open an Image");
    FileFilter filefilter = new FileFilter() {
            @Override
            public boolean accept(File file) {
              String name = file.getName().toLowerCase();
              if(open )
                  return file.isDirectory() || name.endsWith(".jpg") || name.endsWith(".jpeg") 
                          || name.endsWith(".png") || name.endsWith(".bmp");
                          return file.isDirectory() || name.endsWith(".png") || name.endsWith(".bmp");
            }
            @Override
            public String getDescription(){
                if(open)
                    return "Image (*.jpg, *.jpeg, *.png, *.bmp)";
                return "Image (*png , *.bmp)";
            }
        };
          fc.setAcceptAllFileFilterUsed(false);
          fc.addChoosableFileFilter(filefilter);
          
          File file = null;
          if(open && fc.showOpenDialog(this)== fc.APPROVE_OPTION)
              file = fc.getSelectedFile();
          else if(!open && fc.showSaveDialog(this)== fc.APPROVE_OPTION)
              file = fc.getSelectedFile();
          return file;
              
    }
    
    private void btnopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenActionPerformed
         File file = showFileDialog(true);
        if(file == null){
            return; 
        }
        try {
           Image = ImageIO.read(file); 
           jLabelImage.setIcon(new ImageIcon(Image));
            this.validate();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnopenActionPerformed

    private void btndecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecodeActionPerformed
        if(Image == null){
            JOptionPane.showMessageDialog(this,"First Open an Image");
            return;
        }
        int len = extractInteger(Image,0,0);
        byte b[] = new byte[len];
        for(int i=0; i<len;i++){
            b[i]= extractByte(Image, i*8+32,0);
            jTextMessage.setText(new String(b));
        }
    }//GEN-LAST:event_btndecodeActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        Image = null;
        jTextMessage.setText(" ");
        jLabelImage.setIcon(null);
    }//GEN-LAST:event_btnresetActionPerformed

    private byte extractByte(BufferedImage img,int start ,int storageBit){
         int maxX = img.getWidth(), maxY = img.getHeight(),
            startX = start/maxY, startY = start - startX*maxY , count =0;
         byte b =0;
         for(int i=startX;i<maxX && count<8;i++){
        for(int j= startY;j<maxY && count<8; j++){
            int rgb = img.getRGB(i, j), bit = getBitValue(rgb, storageBit);
            b=(byte) setBitValue(b, count, bit);
            count++;
        }
    }
         return b;
     }
    private int extractInteger(BufferedImage img,int start,int storageBit){
    int maxX = img.getWidth(), maxY = img.getHeight(),
            startX = start/maxY, startY = start - startX*maxY , count =0;
    int length = 0;
    for(int i=startX;i<maxX && count<32;i++){
        for(int j= startY;j<maxY && count<32; j++){
            int rgb = img.getRGB(i, j), bit = getBitValue(rgb, storageBit);
            length = setBitValue(length, count, bit);
            count++;
        }
    }
        return length;
    }
    
    
    
     private int getBitValue(int n, int location){
         int v = (int) (n & Math.round(Math.pow(2,location)));
         return v==0?0:1;
     }
             
     private int setBitValue(int n ,int location, int bit){
         int toggle = (int) Math.pow(2,location),bv = getBitValue(n, location);
         if(bv == bit)
             return n;
         if(bv==0 && bit ==1)
             n|= toggle;
         else if(bv==1 && bit==0)
             n ^= toggle;
         return n;
     }
     
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndecode;
    private javax.swing.JButton btnopen;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextMessage;
    // End of variables declaration//GEN-END:variables
}
