    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coding;
import java.awt.image.BufferedImage;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;


/**
 *
 * @author HP
 */
public class Encode_Form extends javax.swing.JFrame {

    /**
     * Creates new form Encode_Form
     */
    BufferedImage sourceImage = null, EmbeddedImage = null; 
    public Encode_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMessage = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabelSourceImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnopen = new javax.swing.JButton();
        btnembed = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextMessage.setColumns(20);
        jTextMessage.setRows(5);
        jScrollPane1.setViewportView(jTextMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Source Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSourceImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelSourceImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Embedded Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnopen.setBackground(new java.awt.Color(255, 51, 255));
        btnopen.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnopen.setForeground(new java.awt.Color(51, 51, 255));
        btnopen.setText("Open");
        btnopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenActionPerformed(evt);
            }
        });

        btnembed.setBackground(new java.awt.Color(255, 51, 255));
        btnembed.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnembed.setForeground(new java.awt.Color(0, 51, 255));
        btnembed.setText("Embed");
        btnembed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnembedActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(255, 51, 255));
        btnsave.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 51, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 51, 255));
        btnreset.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(51, 51, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnopen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnembed, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnopen, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnembed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 private File showFileDialog(final boolean open){
    JFileChooser fc = new JFileChooser("Open an Image");
    FileFilter filefilter = new FileFilter() {
            @Override
            public boolean accept(File file) {
              String name = file.getName().toLowerCase();
              if(open )
                  return file.isDirectory() || name.endsWith(".jpg") || name.endsWith(".jpeg") 
                          || name.endsWith(".png") || name.endsWith(".bmp");
                          return file.isDirectory() || name.endsWith(".png") || name.endsWith(".bmp");
            }
            @Override
            public String getDescription(){
                if(open)
                    return "Image (*.jpg, *.jpeg, *.png, *.bmp)";
                return "Image (*png , *.bmp)";
            }
        };
          fc.setAcceptAllFileFilterUsed(false);
          fc.addChoosableFileFilter(filefilter);
          
          File file = null;
          if(open && fc.showOpenDialog(this)== fc.APPROVE_OPTION)
              file = fc.getSelectedFile();
          else if(!open && fc.showSaveDialog(this)== fc.APPROVE_OPTION)
              file = fc.getSelectedFile();
          return file;
              
    }
    private void btnopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenActionPerformed
        File file = showFileDialog(true);
        if(file == null){
            return; 
        }
        try {
            sourceImage = ImageIO.read(file); 
            jLabelSourceImage.setIcon(new ImageIcon(sourceImage));
            this.validate();
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_btnopenActionPerformed

    private void btnembedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnembedActionPerformed
        if(jTextMessage.equals("") ||sourceImage == null){
            JOptionPane.showMessageDialog(this,"No message has been embedded ", "No Picture or Message found",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Message = jTextMessage.getText();
        EmbeddedImage = sourceImage.getSubimage(0, 0, sourceImage.getWidth(), sourceImage.getHeight());
            embeddedMessage(EmbeddedImage, Message);
            jLabel3.setIcon(new ImageIcon(EmbeddedImage));
            this.validate();
    }//GEN-LAST:event_btnembedActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        jTextMessage.setText(" ");
        sourceImage = null;
        EmbeddedImage = null;
        jLabelSourceImage.setIcon(null);
       jLabel3.setIcon(null);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       if(EmbeddedImage == null){
           JOptionPane.showMessageDialog(this,"No Message has been embedded","Nothing to save",JOptionPane.ERROR_MESSAGE);
           }
       else{
           try {
               File file = showFileDialog(false);
               if(file == null)
                   return;
               
               String name = file.getName();
               String Extention = name.substring(name.lastIndexOf(".")+1).toLowerCase();
               if(!Extention.equals("png") && !Extention.equals("bmp")){
                   Extention = "png";
                   file = new File(file.getAbsoluteFile()+".png");
               }
               if(file.exists()) file.delete();
               ImageIO.write(EmbeddedImage,Extention.toUpperCase(), file);
           } catch (IOException ex) {
              ex.printStackTrace();
           }
       }
    }//GEN-LAST:event_btnsaveActionPerformed
  
     private void embeddedMessage(BufferedImage img, String mess){
         int messageLength = mess.length();
         int imageWidth = img.getWidth();
         int imageHeight = img.getHeight();
         int imageSize = imageWidth * imageHeight;
         
         if(messageLength  *8 +32 > imageSize){
             JOptionPane.showMessageDialog(this,"Message is too long for this Image","Message too Long!", JOptionPane.ERROR_MESSAGE);
             return;
         }
         else{
             embedInteger(img, messageLength,0,0);
             byte b[] = mess.getBytes();
             for(int i=0; i<b.length;i++)
                 embedByte(img,b[i],i*8+32,0);
         }
     }
     private void embedInteger(BufferedImage img, int n, int start, int storageBit){
         int maxX = img.getWidth(), maxY = img.getHeight(),
                 startX = start/maxY , startY = start - startX* maxY, count =0;

      for(int i = startX; i<maxX && count<32; i++){
          for(int j=startY; j<maxY && count<32 ; j++){
              int rgb = img.getRGB(i, j), bit = getBitValue(n, count);
              rgb = setBitValue(rgb, storageBit, bit);
              img.setRGB(i,j,rgb);
              count++;
          }
      }         
     }
     private int getBitValue(int n, int location){
         int v = (int) (n & Math.round(Math.pow(2,location)));
         return v==0?0:1;
     }
             
     private int setBitValue(int n ,int location, int bit){
         int toggle = (int) Math.pow(2,location),bv = getBitValue(n, location);
         if(bv == bit)
             return n;
         if(bv==0 && bit ==1)
             n|= toggle;
         else if(bv==1 && bit==0)
             n ^= toggle;
         return n;
     }
     
    private void embedByte(BufferedImage img, byte b,int start, int storageBit){
        int maxX = img.getWidth(), maxY = img.getHeight(),
                startX = start/maxY, startY = start- startX*maxY, count =0;
        for(int i=startX; i<maxX && count<8 ; i++){
            for(int j= startY; j<maxY && count<8; j++){
                int rgb = img.getRGB(i, j) , bit = getBitValue(b, count);
                rgb = setBitValue(rgb,storageBit, bit);
                img.setRGB(i, j, rgb);
                count++;
            }
        }
        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encode_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encode_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encode_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encode_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encode_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnembed;
    private javax.swing.JButton btnopen;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSourceImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextMessage;
    // End of variables declaration//GEN-END:variables
}
